name: Builder

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  ubuntu1804:
    runs-on: ubuntu-18.04

    env:
      NCNN_VERSION: 20220729
      CPU_PKG_NAME: ncnn-20220729-ubuntu1804
      GPU_PKG_NAME: ncnn-20220729-ubuntu1804-vulkan
      CV_VERSION: 4.6.0
      CV_PKG_NAME: opencv-4.6.0-ubuntu1804

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 安装vulkan
      - name: vulkansdk
        run: |
          wget https://sdk.lunarg.com/sdk/download/1.2.189.0/linux/vulkansdk-linux-x86_64-1.2.189.0.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.2.189.0.tar.gz
          tar -xf vulkansdk-linux-x86_64-1.2.189.0.tar.gz
          rm -rf 1.2.189.0/source 1.2.189.0/samples
          find 1.2.189.0 -type f | grep -v -E 'vulkan|glslang' | xargs rm

      # 下载ncnn-static
      - name: download ncnn-static
        run: |
          cd ncnn-static
          wget https://github.com/benjaminwan/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.CPU_PKG_NAME }}.7z -O ${{ env.CPU_PKG_NAME }}.7z
          7z x ${{ env.CPU_PKG_NAME }}.7z -aoa

      # 下载ncnn-vulkan-static
      - name: download ncnn-vulkan-static
        run: |
          cd ncnn-vulkan-static
          wget https://github.com/benjaminwan/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.GPU_PKG_NAME }}.7z -O ${{ env.GPU_PKG_NAME }}.7z
          7z x ${{ env.GPU_PKG_NAME }}.7z -aoa

      # 下载opencv-static
      - name: download opencv-static
        run: |
          cd opencv-static
          wget https://github.com/RapidAI/OpenCVBuilder/releases/download/${{ env.CV_VERSION }}/${{ env.CV_PKG_NAME }}.7z -O ${{ env.CV_PKG_NAME }}.7z
          7z x ${{ env.CV_PKG_NAME }}.7z -aoa

      # 编译
      - name: build
        run: |
          export VULKAN_SDK=`pwd`/1.2.189.0/x86_64
          export PATH=`pwd`/1.2.189.0/x86_64/bin:$PATH
          chmod a+x build-default.sh &&./build-default.sh

      # 使用7z压缩
      - name: 7zip
        run: |
          mkdir linux-bin
          cp run-benchmark.sh linux-bin/run-benchmark.sh
          cp run-test.sh linux-bin/run-test.sh
          cp -r images linux-bin/images
          mv Linux-BIN-CPU/install/bin linux-bin/Linux-BIN-CPU
          mv Linux-BIN-GPU/install/bin linux-bin/Linux-BIN-GPU
          7z a linux-bin.7z linux-bin
          mkdir linux-jni
          mv Linux-JNI-CPU/install linux-jni/Linux-JNI-CPU
          mv Linux-JNI-GPU/install linux-jni/Linux-JNI-GPU
          7z a linux-jni.7z linux-jni
          mkdir linux-clib
          mv Linux-CLIB-CPU/install linux-clib/Linux-CLIB-CPU
          mv Linux-CLIB-GPU/install linux-clib/Linux-CLIB-GPU
          7z a linux-clib.7z linux-clib

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: linux-bin
          path: linux-bin.7z

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: linux-jni
          path: linux-jni.7z

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: linux-clib
          path: linux-clib.7z

  macos1015:
    runs-on: macos-latest

    env:
      NCNN_VERSION: 20220729
      CPU_PKG_NAME: ncnn-20220729-macos1015
      GPU_PKG_NAME: ncnn-20220729-macos1015-vulkan
      CV_VERSION: 4.6.0
      CV_PKG_NAME: opencv-4.6.0-macos1015

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 安装openmp
      - name: install openmp
        run: |
          brew install libomp

      # 安装vulkan
      - name: vulkansdk
        run: |
          wget https://sdk.lunarg.com/sdk/download/1.2.189.0/mac/vulkansdk-macos-1.2.189.0.dmg?Human=true -O vulkansdk-macos-1.2.189.0.dmg
          hdiutil attach vulkansdk-macos-1.2.189.0.dmg
          sudo /Volumes/vulkansdk-macos-1.2.189.0/InstallVulkan.app/Contents/MacOS/InstallVulkan --root $GITHUB_WORKSPACE/vulkansdk-macos-1.2.189.0 --accept-licenses --default-answer --confirm-command install
          hdiutil detach /Volumes/vulkansdk-macos-1.2.189.0

      # 下载ncnn-static
      - name: download ncnn-static
        run: |
          cd ncnn-static
          wget https://github.com/benjaminwan/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.CPU_PKG_NAME }}.7z -O ${{ env.CPU_PKG_NAME }}.7z
          7z x ${{ env.CPU_PKG_NAME }}.7z -aoa

      # 下载ncnn-vulkan-static
      - name: download ncnn-vulkan-static
        run: |
          cd ncnn-vulkan-static
          wget https://github.com/benjaminwan/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.GPU_PKG_NAME }}.7z -O ${{ env.GPU_PKG_NAME }}.7z
          7z x ${{ env.GPU_PKG_NAME }}.7z -aoa

      # 下载opencv-static
      - name: download opencv-static
        run: |
          cd opencv-static
          wget https://github.com/RapidAI/OpenCVBuilder/releases/download/${{ env.CV_VERSION }}/${{ env.CV_PKG_NAME }}.7z -O ${{ env.CV_PKG_NAME }}.7z
          7z x ${{ env.CV_PKG_NAME }}.7z -aoa

      # 编译
      - name: build
        run: |
          export VULKAN_SDK=$GITHUB_WORKSPACE/vulkansdk-macos-1.2.189.0/macOS
          chmod a+x build-default.sh &&./build-default.sh

      # 使用7z压缩
      - name: 7zip
        run: |
          mkdir macos-bin
          cp run-benchmark.sh macos-bin/run-benchmark.sh
          cp run-test.sh macos-bin/run-test.sh
          cp -r images macos-bin/images
          mv Darwin-BIN-CPU/install/bin macos-bin/Darwin-BIN-CPU
          mv Darwin-BIN-GPU/install/bin macos-bin/Darwin-BIN-GPU
          7z a macos-bin.7z macos-bin
          mkdir macos-jni
          mv Darwin-JNI-CPU/install macos-jni/Darwin-JNI-CPU
          mv Darwin-JNI-GPU/install macos-jni/Darwin-JNI-GPU
          7z a macos-jni.7z macos-jni
          mkdir macos-clib
          mv Darwin-CLIB-CPU/install macos-clib/Darwin-CLIB-CPU
          mv Darwin-CLIB-GPU/install macos-clib/Darwin-CLIB-GPU
          7z a macos-clib.7z macos-clib

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: macos-bin
          path: macos-bin.7z

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: macos-jni
          path: macos-jni.7z

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: macos-clib
          path: macos-clib.7z

  windows-vs2019:
    runs-on: windows-2019

    env:
      NCNN_VERSION: 20220729
      CPU_PKG_NAME: ncnn-20220729-windows-vs2019-mt
      GPU_PKG_NAME: ncnn-20220729-windows-vs2019-vulkan-mt
      CV_VERSION: 4.6.0
      CV_PKG_NAME: opencv-4.6.0-windows-vs2019-mt

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 安装vulkan
      - name: vulkansdk
        run: |
          Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.2.189.0/windows/VulkanSDK-1.2.189.0-Installer.exe?Human=true -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
          $installer.WaitForExit();

      # 下载ncnn-static
      - name: download ncnn-static
        run: |
          cd ncnn-static
          Invoke-WebRequest -Uri https://github.com/benjaminwan/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.CPU_PKG_NAME }}.7z -OutFile ${{ env.CPU_PKG_NAME }}.7z
          7z x ${{ env.CPU_PKG_NAME }}.7z -aoa

      # 下载ncnn-vulkan-static
      - name: download ncnn-vulkan-static
        run: |
          cd ncnn-vulkan-static
          Invoke-WebRequest -Uri https://github.com/benjaminwan/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.GPU_PKG_NAME }}.7z -OutFile ${{ env.GPU_PKG_NAME }}.7z
          7z x ${{ env.GPU_PKG_NAME }}.7z -aoa

      # 下载opencv-static
      - name: download opencv-static
        run: |
          cd opencv-static
          Invoke-WebRequest -Uri https://github.com/RapidAI/OpenCVBuilder/releases/download/${{ env.CV_VERSION }}/${{ env.CV_PKG_NAME }}.7z -OutFile ${{ env.CV_PKG_NAME }}.7z
          7z x ${{ env.CV_PKG_NAME }}.7z -aoa

      # 编译
      - name: build
        run: |
          $env:VULKAN_SDK="C:/VulkanSDK/1.2.189.0"
          $env:Path+=";C:/VulkanSDK/1.2.189.0/Bin"
          ./build-default.bat

      # 使用7z压缩
      - name: 7zip
        run: |
          mkdir windows-bin
          cp run-benchmark.bat windows-bin/run-benchmark.bat
          cp run-test.bat windows-bin/run-test.bat
          cp -r images windows-bin/images
          mv win-BIN-CPU-x64/install/bin windows-bin/win-BIN-CPU-x64
          mv win-BIN-CPU-Win32/install/bin windows-bin/win-BIN-CPU-Win32
          mv win-BIN-GPU-x64/install/bin windows-bin/win-BIN-GPU-x64
          mv win-BIN-GPU-Win32/install/bin windows-bin/win-BIN-GPU-Win32
          7z a windows-bin.7z windows-bin
          mkdir windows-jni
          mv win-JNI-CPU-x64/install windows-jni/win-JNI-CPU-x64
          mv win-JNI-CPU-Win32/install windows-jni/win-JNI-CPU-Win32
          mv win-JNI-GPU-x64/install windows-jni/win-JNI-GPU-x64
          mv win-JNI-GPU-Win32/install windows-jni/win-JNI-GPU-Win32
          7z a windows-jni.7z windows-jni
          mkdir windows-clib
          mv win-CLIB-CPU-x64/install windows-clib/win-CLIB-CPU-x64
          mv win-CLIB-CPU-Win32/install windows-clib/win-CLIB-CPU-Win32
          mv win-CLIB-GPU-x64/install windows-clib/win-CLIB-GPU-x64
          mv win-CLIB-GPU-Win32/install windows-clib/win-CLIB-GPU-Win32
          7z a windows-clib.7z windows-clib

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: windows-bin
          path: windows-bin.7z

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: windows-jni
          path: windows-jni.7z

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: windows-clib
          path: windows-clib.7z

  release:
    needs: [ ubuntu1804, macos1015, windows-vs2019 ]

    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 获取所有的git log和tag
      - name: Unshallow
        run: git fetch --prune --unshallow

      # 获取git log 从 previousTag 到 lastTag
      - name: Get git log
        id: git-log
        run: |
          previousTag=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          lastTag=$(git describe --abbrev=0 --tags)
          echo "previousTag:$previousTag ~ lastTag:$lastTag"
          log=$(git log $previousTag..$lastTag --pretty=format:'- %cd %an: %s\n' --date=format:'%Y-%m-%d %H:%M:%S')
          echo "$log"
          echo "log_state="$log"" >> $GITHUB_ENV

      # 创建Changelog文件 triggered by git tag push
      - name: Generate Changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo -e '${{ env.log_state }}' > Release.txt

      # Cat Changelog triggered by git tag push
      - name: Cat Changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cat Release.txt

      # 下载artifact
      - name: download
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      # 查看artifact
      - name: list artifact
        run: |
          tree artifacts

      # 创建release
      - name: create-release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: Release.txt
          draft: false
          prerelease: false

      - name: upload-linux-bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: linux-bin
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-linux-jni
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: linux-jni
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-linux-clib
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: linux-clib
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-macos-bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: macos-bin
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-macos-jni
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: macos-jni
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-macos-clib
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: macos-clib
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-windows-bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: windows-bin
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-windows-jni
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: windows-jni
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-windows-clib
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: windows-clib
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      # 获取指定时区的时间
      # https://github.com/marketplace/actions/get-time-action
      - name: Get Time
        id: time
        uses: JantHsueh/get-time-action@master
        with:
          timeZone: 8

      # 向钉钉发送消息
      # https://github.com/marketplace/actions/web-request-action
      - name: dingtalk
        uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK }}
          method: POST
          payload: '{"msgtype": "text", "text": {"content": "版本更新: ${{ github.repository }}-版本号: ${{ github.ref }} \n 编译时间： ${{ steps.time.outputs.time }} \n 距上个正式版的更新记录: \n${{ env.log_state }}"}}'
          headers: '{"Content-Type": "application/json"}'